### PR TITLE
play audio and video media 'direct' with html5, avoid using jw player…

### PR DESCRIPTION
**Pull request by st-anton**
… framework if it is not needed

if you want to integrate this, please feel free. This is a first step to use html5 for medias, Brent want to go further as I read in the mail.

### CODE REVIEW

**Comment by st-anton** [comment]
wrong branch :-(

**Comment by st-anton** [comment]
Reviewed the pull request and file, they are the right one

**Comment by bcordis** [comment]
@st-anton Great work. I'll start reviewing the cod now.

**Comment by bcordis** [comment]
Please update brach so it is inline with development thanks.

**Pull request closed without merging**
