### PR TITLE
New mod_proclaimicon for Admin View.

### PR DESCRIPTION
**Pull request by bcordis**

### CODE REVIEW

**Review by tomfuller2 — APPROVED** [review]
Let's test

**Review by tomfuller2 — APPROVED** [review]
APPROVED

**Comment by bcordis** [comment]
@tomfuller2 Should we install this by default when we install?

**Comment by tomfuller2** [comment]
Yes!

Tom Fuller, APR
Imagine Communications <http://www.ImagineCommunications.xyz>
971-832-9494

**Pull request merged**
